---
title: '20200404'
author: "oscar"
date: "2020/4/4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# 108-1 
course1_1081 <- 
  list(
    name="個體經濟學",
    teacher="Alice",
    grade=85
  )
course2_1081 <-
  list(
    name="總體經濟學",
    teacher="Mark",
    grade=78
  )
`108-1修課記錄` <- 
  list(
    course1_1081,
    course2_1081
  )

# 108-2
course1_1082 <- 
  list(
    name="作業研究",
    teacher="Jason",
    grade=90
  )
`108-2修課記錄` <- 
  list(
    course1_1082
  )

# 整合兩學期
`每學期修課記錄` <- list(
  `108-1`=`108-1修課記錄`,
  `108-2`=`108-2修課記錄`
)

# 完成記錄
`小明的修課記錄` <- 
  list(
    name="小明",
    semesters=`每學期修課記錄`
  )
```
```{r}
library(lubridate)

object1 <- c(2,5)
object2 <- ymd_hms(
  c("2015-03-22 12:28:42","2017-12-22 15:33:48"),
  tz="Asia/Taipei"
)
object3 <- list(2, FALSE, c("a","b","c"))
save(object1, object2, object3, file="threeObjects.Rda")
load("threeObjects.Rda")
```

```{r}
Prisoners_dillemma=list(
  players_of_the_game=list(
    name1="A",
    name2="B"),
  each_players_strategy=list(
    A=list(
      strategy1="stay_silent",
      strategy2="betray"),
    B_strategy=list(
      strategy1="stay_silent",
      strategy2="betray")),
  eventual_outcome=list(
    `A:strategy1`=list(
      `B:strategy1`=list(Aconsequence=c(-1),Bconsequence=c(-1)),
      `B:strategy2`=list(Aconsequence=-3,Bconsequence=0)),
    `A:strategy2`=list(
      `B:strategy1`=list(Aconsequence=0,Bconsequence=-3),
      `B:strategy2`=list(Aconsequence=-2,Bconsequence=-2))
    )
)

Prisoners_dillemma$each_players_strategy$A$strategy1 # 查A的strategy1
Prisoners_dillemma$each_players_strategy$A$strategy2
Prisoners_dillemma$each_players_strategy$B$strategy1
Prisoners_dillemma$each_players_strategy$B$strategy2

Prisoners_dillemma$eventual_outcome$`A:strategy1`$`B:strategy2` # `A:strategy1`$`B:strategy2`下的payoff
```

```{r}
library(jsonlite)
toJSON(Prisoners_dillemma)
```
```{r}
library(jsonlite)
fromJSON("https://opendata.cwb.gov.tw/fileapi/v1/opendataapi/F-C0032-001?Authorization=rdec-key-123-45678-011121314&format=JSON") ->
  weather_next36hours
  
  
)
```

```{r}
yy <- 2020
mm <- 03
dd <- 15
event_list <- list(
  list(time=ymd("yy,mm,dd")),
  list(name="小明","是否完成" = "True","完成所花時間(秒)" = 350,tools=c("anchor","axe"))
     )
```

