---
title: '20200325'
author: "oscar"
date: "2020/3/25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(readr)
library(googlesheets4)
library(dplyr)
library(lubridate)
```
```{r}
majors10_factor <- factor(
  c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')
)
##這裡有轉成可計算函數函數
##numeric&intergar
typeof(majors10_factor)
class(majors10_factor)
hellomyfriend <- as.integer(majors10_factor)
hellomyfriend+22
levels(majors10_factor)
class(hellomyfriend)
```
```{r}
stringInteger <- c("1","2","-11")
##class(stringInteger) # 無法進行數值運算
##stringInteger+2
trueInteger <- as.integer(stringInteger)
class(trueInteger) # 可以進行數值運算
typeof(trueInteger)
trueInteger+2
```
```{r}
studentId <- c(410773002, 410773015)
opop <- as.character(studentId)
class(opop)
```


```{r}

##ymd_hms(..., tz="Asia/Taipei")
##with_tz(..., tzone="Asia/Taipei")
library(lubridate)
pgTime <- mdy_hms("Mar.18, 2020, 05:52:40",
                  tz="Europe/Lisbon")
tpetime <-  ymd_hms("2020-03-18 13:52:40",
        tz="Asia/Taipei")
tpetime <- ymd_hms(tpetime, tz="Asia/Taipei")
with_tz(tpetime, tzone="UTC")
with_tz(pgTime, tzone="UTC")
tpe11 <- as.double(tpetime)
tpe <- as.numeric(tpe11)
typeof(tpe)
pg11 <- as.double(pgTime)
pg <- as.numeric(pg11)
class(pg)
if (tpe>pg){
  print("ok")
  } else
  {print("not ok")}
```
```{r}
nigga <- 
  c(ymd_hms("2020-03-04T05:59:15Z"),
    (md_hms ("2020-03-11 14:15:03","2020-03-11 14:33:55"), tz="Asia/Taipei")
nigga 
niggas <- as.numeric(nigga)
niggas
```




