---
title: '20200411'
author: "oscar"
date: "2020/4/12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
listExample <- 
  list(
    student="小明",
    `學期`=list(
      `108-1`=list(
        list(
          name="個體經濟學",
          teacher="Alice",
          grade=85
        )
      ),
      `108-2`=list(
        list(
          name="總體經濟學",
          teacher="Mark",
          grade=78
        )
      )
    )
  )
# 有多少位置可選：
length(listExample)


# 有多少名字可選：
names(listExample)
listExample$student
listExample$`學期` # 特殊命名依然要用反頓點呼叫
```
```{r}
str(listExample$`學期`)
```
```{r}
# 顯示到第一層
str(listExample, max.level=1)
listExample[c(1,2)]
```
```{r}
fromJSON("http://data.ntpc.gov.tw/api/v1/rest/datastore/382000000A-000157-002",
         simplifyDataFrame = F) -> newTaipeiCityVaccine
```

```{r}
length(newTaipeiCityVaccine)
names(newTaipeiCityVaccine)
```
```{r}
newTaipeiCityVaccine[[1]]
str(newTaipeiCityVaccine[["result"]], max.level = 1)
```


```{r}
vectorExample <- c("小明","小英","大雄")

# 有多少位置可選：
#length(vectorExample)
#vectorExample
#vectorExample[c(1,3)]
blabla <- vectorExample[c(3,2,1)] # 產生重新排列效果
print(blabla)

```

```{r}
yy <- 2020
mm <- 03
dd <- 15
event_list <- list(
  time=ymd("2020-03-15"),
  list(name="小明",`是否完成`= "True",`完成所花時間(秒)`=350,tools=c("anchor","axe"))
  )
    #`是否完成`=True,
    #完成所花時間(秒)=350,
    #tools=c("anchor","axe")
print(event_list)
```
```{r}

# list含兩個lists, 子層list又各含兩個vectors
`小明108學年課表C` <- list(
list(
    c("108-1"), # 可只寫 "108-1"
    c("高級會計學","高等統計學")
       ),
list(
    c("108-2"),
    c("食在拉丁美洲")
  )
)
print(`小明108學年課表C`)

```
```{r}
yy <- 2020
mm <- 03
dd <- 15
time=ymd("yy,mm,dd")
print(time)
```
yy <- 2020
mm <- `Mar.`
dd <- 15
event_list <- list(
  time=ymd(paste0(yy,",",mm,dd)),
  list(
    name="小明",
    `是否完成`=True,
    完成所花時間(秒)=350,
    tools=c(
      "anchor","axe")
)



















